# MLP Classifier

In [1]:
#importing libraries
import numpy as np
from sklearn import datasets, metrics
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [2]:
#loading the dataset
X,y = datasets.load_iris(return_X_y=True)

### applying variations to MLPClassifier and comparing the accuracy 

In [3]:
#splitting into train an test dataset
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 1
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 200, activation='relu', learning_rate = 'constant').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (75, 4)
test set shape: (75, 4)
Prediction:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Probabilities of each class: 
 [[0.86403485 0.11404547 0.02191968]
 [0.84601107 0.12774237 0.02624655]
 [0.90668393 0.08197995 0.01133612]
 [0.88948811 0.09500395 0.01550794]
 [0.86302626 0.11605391 0.02091983]
 [0.86805826 0.11197713 0.01996461]
 [0.88291962 0.09640865 0.02067173]
 [0.95066197 0.04453663 0.00480141]
 [0.90790366 0.079429   0.01266733]
 [0.91712937 0.07238422 0.01048642]
 [0.90750855 0.0799684  0.01252305]
 [0.83418018 0.13760273 0.02821709]
 [0.83189105 0.14026627 0.02784268]
 [0.90268133 0.0846283  0.01269036]
 [0.84292035 0.13104683 0.02603282]
 [0.89277425 0.09224069 0.01498506]
 [0.94518628 0.04922621 0.00558751]
 [0.90707155 0.07912811 0.01380034]
 [0.90998183 0.07816033 0.01185784]
 [0.89237286 0.09285095 0.01477619]
 [0.76566084 0.18049734 0.053841

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [4]:
#splitting into train an test dataset
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 2
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(100), max_iter= 200, activation='logistic', learning_rate = 'adaptive').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (75, 4)
test set shape: (75, 4)
Prediction:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Probabilities of each class: 
 [[0.41993059 0.29947196 0.28059745]
 [0.41908007 0.2993124  0.28160753]
 [0.41435445 0.30771055 0.277935  ]
 [0.42066614 0.3011573  0.27817656]
 [0.41927174 0.2994232  0.28130506]
 [0.41815556 0.30143674 0.28040771]
 [0.43519878 0.29197441 0.27282681]
 [0.42560149 0.30651495 0.26788356]
 [0.42317702 0.30166858 0.27515439]
 [0.4232206  0.30285288 0.27392652]
 [0.42038395 0.30409473 0.27552133]
 [0.40711638 0.30754934 0.28533428]
 [0.41246858 0.30219587 0.28533555]
 [0.42086575 0.3020388  0.27709545]
 [0.41627452 0.30093978 0.28278569]
 [0.41542681 0.30535297 0.27922023]
 [0.43104727 0.30204285 0.26690988]
 [0.42880274 0.29760475 0.27359251]
 [0.42868712 0.29831357 0.2729993 ]
 [0.42017755 0.30159416 0.27822829]
 [0.41544607 0.29743523 0.287118

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [5]:
#splitting into train an test dataset
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 3
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 200, activation='identity', learning_rate = 'invscaling').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (75, 4)
test set shape: (75, 4)
Prediction:
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 1 1 2 1 1 2 2 1 2 1 2 2 2 2 2 1 2 2 1 2 1 2
 2]

Probabilities of each class: 
 [[0.37963126 0.21314702 0.40722172]
 [0.34598269 0.207525   0.44649231]
 [0.36348812 0.15533711 0.48117476]
 [0.36245127 0.18345086 0.45409787]
 [0.36173845 0.2048786  0.43338296]
 [0.33961083 0.18523952 0.47514964]
 [0.35637408 0.20538535 0.43824058]
 [0.37628924 0.12211573 0.50159503]
 [0.37997667 0.17617111 0.44385222]
 [0.35706392 0.156851   0.48608509]
 [0.36810173 0.16579792 0.46610035]
 [0.37419984 0.20182951 0.42397065]
 [0.36968527 0.2175428  0.41277193]
 [0.37274524 0.17585622 0.45139854]
 [0.34084922 0.2011973  0.45795348]
 [0.40403172 0.18679979 0.40916848]
 [0.36801605 0.12862865 0.5033553 ]
 [0.39682829 0.19244347 0.41072824]
 [0.34843959 0.16485039 0.48671003]
 [0.36979066 0.18336325 0.44684609]
 [0.38433451 0.27674448 0.338921

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [6]:
#splitting into train an test dataset
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 4
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 200, activation='identity', learning_rate = 'adaptive').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (75, 4)
test set shape: (75, 4)
Prediction:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Probabilities of each class: 
 [[8.82977981e-01 1.11915539e-01 5.10648019e-03]
 [8.73861015e-01 1.18801648e-01 7.33733731e-03]
 [9.13860396e-01 8.28857930e-02 3.25381096e-03]
 [9.08010682e-01 8.82153428e-02 3.77397525e-03]
 [8.92762279e-01 1.02549802e-01 4.68791889e-03]
 [8.94445784e-01 1.00083410e-01 5.47080645e-03]
 [9.12555621e-01 8.31597665e-02 4.28461251e-03]
 [9.56285370e-01 4.27082929e-02 1.00633753e-03]
 [9.16107402e-01 8.08199539e-02 3.07264372e-03]
 [9.27515992e-01 6.97454927e-02 2.73851483e-03]
 [9.12211033e-01 8.41767058e-02 3.61226085e-03]
 [8.37770035e-01 1.53102324e-01 9.12764068e-03]
 [8.60694537e-01 1.32590670e-01 6.71479306e-03]
 [9.18326021e-01 7.88393244e-02 2.83465416e-03]
 [8.73886182e-01 1.18818873e-01 7.29494460e-03]
 [8.94158438e-01 1.02154393e-01 

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [7]:
#splitting into train an test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 5
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 200, activation='tanh', learning_rate = 'adaptive').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (112, 4)
test set shape: (38, 4)
Prediction:
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]

Probabilities of each class: 
 [[0.04699546 0.52060925 0.43239529]
 [0.89079756 0.09292992 0.01627252]
 [0.00637106 0.27576854 0.7178604 ]
 [0.05718571 0.50083839 0.4419759 ]
 [0.04251367 0.55714658 0.40033975]
 [0.86948675 0.11141994 0.01909331]
 [0.15476229 0.54961725 0.29562047]
 [0.03250627 0.42363438 0.54385935]
 [0.03397942 0.54727939 0.41874119]
 [0.09654193 0.57835455 0.32510352]
 [0.03587524 0.4099018  0.55422296]
 [0.84742497 0.12958519 0.02298984]
 [0.91025001 0.07765315 0.01209683]
 [0.84467716 0.13156437 0.02375847]
 [0.91544399 0.07087072 0.01368529]
 [0.0643707  0.4785042  0.4571251 ]
 [0.01512061 0.30422483 0.68065456]
 [0.08246793 0.58256451 0.33496756]
 [0.05439423 0.49597315 0.44963263]
 [0.01570115 0.32466709 0.65963176]
 [0.83852502 0.13421937 0.02725561]
 [0.03820755 0.42412779 0.53766466]
 [0.85723848 0.11919384 0.02356768

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [8]:
#splitting into train an test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=20)

print("train set shape:",X_train.shape)
print("test set shape:",X_test.shape)

#variation 6
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(50), max_iter= 100, activation='relu', learning_rate = 'constant').fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
print("Prediction:\n",prediction)
print()
print("Probabilities of each class: \n",classifier.predict_proba(X_test))
print()
print("Accuracy:\n",metrics.accuracy_score(y_test,prediction,normalize = True))
print()
print("Classification report:\n",metrics.classification_report(y_test,prediction))
print()
print("Confusion matrix:\n",metrics.confusion_matrix(y_test,prediction))

train set shape: (100, 4)
test set shape: (50, 4)
Prediction:
 [0 2 1 2 1 2 2 0 2 0 2 2 2 0 0 2 0 2 2 1 1 2 2 0 2 1 1 0 2 2 1 1 0 0 0 2 2
 0 2 2 2 2 0 1 2 0 0 0 2 0]

Probabilities of each class: 
 [[0.66137911 0.25850284 0.08011805]
 [0.13980989 0.41547715 0.44471297]
 [0.20337473 0.40977052 0.38685475]
 [0.07866156 0.36123997 0.56009847]
 [0.20416449 0.43350095 0.36233456]
 [0.16573377 0.40621377 0.42805246]
 [0.04520059 0.2669214  0.68787802]
 [0.69995035 0.22817475 0.0718749 ]
 [0.04878821 0.31516595 0.63604584]
 [0.67185108 0.25369077 0.07445814]
 [0.07876736 0.32219072 0.59904192]
 [0.15081545 0.40010564 0.44907891]
 [0.07629332 0.36326644 0.56044024]
 [0.71712227 0.21589031 0.06698741]
 [0.71593056 0.22001201 0.06405743]
 [0.03402977 0.2833548  0.68261543]
 [0.67127739 0.24845796 0.08026464]
 [0.17588505 0.41091484 0.4132001 ]
 [0.05099882 0.2599666  0.68903458]
 [0.24145555 0.42465735 0.3338871 ]
 [0.1967048  0.40420935 0.39908585]
 [0.07851909 0.33450329 0.58697762]
 [0.065612

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


### comparing the outputs of different variations

|X_train shape|X_test shape|Hidden layers|Max iterations|Activation function|Learning rate|Accuracy|
|-------------|------------|-------------|--------------|-------------------|-------------|--------|
|75,4         |75,4        |65           |200           |relu               |constant     |0.9734|
|75,4         |75,4        |100           |200           |logistic               |adaptive     |0.667|
|75,4         |75,4        |65           |200           |identity               |iinvscaling     |0.24|
|75,4         |75,4        |65           |200           |identity               |adaptive     |0.9867|
|112,4(random state = 42)         |38,4(random state = 42)        |65           |200           |tanh     |adaptive     |1|
|100,4(random state = 20)        |50,4(random state = 20)        |50           |100           |relu |constant     |0.82|

# K-mean clustering

In [9]:
#importing libraries
from sklearn import datasets,metrics
from sklearn.cluster import KMeans

#loading the dataset
X,y = datasets.load_iris(return_X_y=True)

#train and test set
X_train = X[0:100,:]
X_test = X[100:,:]

#defining the model with 3 clusters, 3 centroids 
model = KMeans(n_clusters=3).fit(X_train)

#print label for each point
print("Labels:\n",model.labels_)

#print prediction on test set
prediction = model.predict(X_test)
print("Prediction:\n",prediction)

#printing coordinates of cluster centers
print("Cluster Center:\n",model.cluster_centers_)

Labels:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 1 2 1 2 1 2 1 1 1 1 2 1 2 1 1 2 1 2 1 2 2
 2 2 2 2 2 1 1 1 1 2 1 2 2 2 1 1 1 2 1 1 1 1 1 2 1 1]
Prediction:
 [2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
Cluster Center:
 [[5.006      3.428      1.462      0.246     ]
 [5.55555556 2.64074074 3.94074074 1.21111111]
 [6.3826087  2.92173913 4.63478261 1.46086957]]


In [10]:
#train and test set
X_train = X[range(0,150,2),:]
X_test = X[range(1,150,2),:]

#defining the model with 4 clusters, 4 centroids 
model = KMeans(n_clusters = 4).fit(X_train)

#print label for each point
print("Labels:\n",model.labels_)

#print prediction on test set
prediction = model.predict(X_test)
print("Prediction:\n",prediction)

#printing coordinates of cluster centers
print("Cluster Center:\n",model.cluster_centers_)

Labels:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 3 3 3 3 0 0 0
 0 0 0 3 3 3 0 3 3 3 3 3 3 2 2 2 3 2 0 2 0 2 2 2 2 2 0 2 2 2 0 2 0 2 0 2 0
 2]
Prediction:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 3 3 3 3 3 0 0 3 3 3 0
 0 0 3 3 0 0 0 3 0 3 3 0 3 0 2 2 2 2 0 0 2 2 0 0 0 2 0 2 2 0 2 2 2 2 2 2 0
 0]
Cluster Center:
 [[6.33157895 2.86842105 4.81578947 1.63157895]
 [5.024      3.48       1.456      0.228     ]
 [6.76470588 3.01764706 5.82941176 2.17647059]
 [5.50714286 2.64285714 4.01428571 1.26428571]]
