In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.datasets import load_boston

In [2]:
X,y = load_boston(return_X_y=True)

In [3]:
X_train = X[0:400, : ]

temp = np.zeros((X_train.shape[0], X_train.shape[1] + 1))
temp[:,0] = np.ones(X_train.shape[0])
temp[:,1:] = X_train
X_train = temp
print(X_train.shape)

(400, 14)


In [4]:
y_train = y[0:400]
y_train.shape

(400,)

In [5]:
lamba = 10
mat = np.identity(X_train.shape[1])
mat[0,0] = 0
print(mat)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:
theta = np.zeros(X_train.shape[1])
print(theta)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
XTXi = inv(np.dot(X_train.T,X_train) + lamba*mat)
XTXi

array([[ 1.07161048e+00,  1.18028140e-03,  5.22390451e-07,
        -1.75289329e-03, -3.28742242e-03, -7.07692080e-02,
        -6.79419664e-02, -1.86306880e-04, -1.09456123e-02,
         4.45467860e-03, -2.32586517e-04, -1.28932859e-02,
        -5.19719630e-04, -4.18124625e-03],
       [ 1.18028140e-03,  1.25378469e-04, -1.25725193e-06,
        -1.12436604e-06,  1.53871961e-04,  4.65597199e-05,
        -1.33442207e-04,  2.65545723e-06,  2.88951248e-05,
        -6.11733926e-05, -4.24873812e-07,  3.66588127e-06,
        -1.30809893e-08, -3.22551855e-05],
       [ 5.22390451e-07, -1.25725193e-06,  8.53638429e-06,
         3.58969447e-06, -1.90847006e-06,  1.56573143e-05,
        -4.41120132e-05,  1.27235387e-06, -5.18085583e-05,
         3.47329633e-06, -5.46068178e-07,  2.50994224e-05,
        -3.51938639e-08, -1.59388575e-06],
       [-1.75289329e-03, -1.12436604e-06,  3.58969447e-06,
         1.68341114e-04, -2.32185032e-04, -4.01567808e-04,
         1.41618782e-04, -1.86122401e-06,  1.

In [8]:
XTy = np.dot(X_train.T,y_train)
XTy

array([9.73380000e+03, 1.12273125e+04, 1.68607800e+05, 8.27518650e+04,
       9.95400000e+02, 5.03368551e+03, 6.36958714e+04, 5.94267320e+05,
       4.17565881e+04, 5.99485000e+04, 3.25857470e+06, 1.71715830e+05,
       3.71919609e+06, 9.21525960e+04])

In [9]:
theta = np.dot(XTXi,XTy)
theta

array([ 2.11514182e+01, -1.79608935e-01,  4.82645634e-02, -6.30345823e-03,
        1.29041370e+00, -1.51210627e+00,  4.57344143e+00, -4.78507021e-03,
       -1.12701053e+00,  4.59780103e-01, -1.77414680e-02, -6.83427205e-01,
        3.79004608e-03, -5.65193198e-01])

In [10]:
prediction = np.dot(theta,X_train.T)
prediction

array([29.78136531, 24.58284532, 31.03484417, 29.88758528, 29.18003707,
       25.94367427, 22.67421904, 19.02199996, 10.23710722, 18.69482682,
       18.75586567, 21.35661144, 20.49312506, 20.65605991, 20.30069333,
       20.26779136, 21.8182289 , 17.56595587, 17.16998374, 18.88393359,
       12.37351735, 18.17700968, 16.19888145, 13.90044093, 16.15863604,
       14.17101783, 16.14097346, 15.76176172, 20.65641259, 22.14515287,
       11.62286455, 18.72765862,  9.62070783, 14.45910739, 14.66120458,
       23.62900352, 22.16389069, 23.24183537, 23.12550219, 31.53055014,
       34.84271065, 28.64577344, 25.32093598, 24.63105791, 22.61614245,
       21.22188148, 19.47000815, 17.02107523,  7.10817979, 16.21417834,
       20.76589481, 23.65247373, 28.01887019, 23.89158136, 14.35260294,
       32.96072474, 25.07880931, 33.63608037, 23.54930029, 22.15999242,
       18.65148844, 19.21127428, 25.55606849, 24.64745046, 24.9413982 ,
       29.33551212, 23.82187564, 20.26971705, 16.06552404, 19.84