# Grid Search

In [3]:
#importing libraries
import numpy as np
from sklearn import neighbors,datasets,metrics
from sklearn .model_selection import GridSearchCV

#loading dataset
X,y = datasets.load_iris(return_X_y= True)

#splitting to test and train dataset
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

#defining classifier
classifier = neighbors.KNeighborsClassifier()

#parameter values
param_grid = {'n_neighbors' : [1,5,10,15], 'weights' : ['uniform','distance']}

#computing grid search
clf = GridSearchCV(classifier, param_grid, cv = 5)
clf.fit(X_train,y_train)

#printing the best parameters
print("Best choice",clf.best_params_)

#predicting on test set
prediction = clf.predict(X_test)
print("\nPrediction",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Best choice {'n_neighbors': 5, 'weights': 'uniform'}

Prediction [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Accuracy score :-
 0.9866666666666667

Classification report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75


Confusion Matrix :-
 [[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]


# Linear SVM

In [5]:
#importing libraries
import numpy as np
from sklearn import svm,datasets,metrics
import matplotlib.pyplot as plt

#loading datasets
X,y = datasets.load_iris(return_X_y= True)

#splitting to test and train
X_train = X[range(1,150,1),:]
y_train = y[range(1,150,1)]

X_test = X[range(0,150,2),:]
y_test = y[range(0,150,2)]

#computing SVM
classifier = svm.LinearSVC().fit(X_train,y_train)

#prediction and error
prediction = classifier.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Prediction :- 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 1 1 2 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]

Accuracy score :-
 0.9733333333333334

Classification report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.92      0.96        25
           2       0.93      1.00      0.96        25

    accuracy                           0.97        75
   macro avg       0.98      0.97      0.97        75
weighted avg       0.98      0.97      0.97        75


Confusion Matrix :-
 [[25  0  0]
 [ 0 23  2]
 [ 0  0 25]]


C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
