In [1]:
import numpy as np
from sklearn import neighbors,datasets,metrics
from sklearn .model_selection import GridSearchCV

In [3]:
X,y = datasets.load_iris(return_X_y= True)

In [9]:
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

In [18]:
classifier = neighbors.KNeighborsClassifier()

param_grid = {'n_neighbors' : [1,5,10,15], 'weights' : ['uniform','distance']}

clf = GridSearchCV(classifier, param_grid, cv = 5)
clf.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'n_neighbors': [1, 5, 10, 15],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [19]:
clf.best_params_

{'n_neighbors': 5, 'weights': 'uniform'}

In [22]:
prediction = clf.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))


Accuracy score :-
 0.9733333333333334

Classification report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.96      0.96      0.96        25
           2       0.96      0.96      0.96        25

    accuracy                           0.97        75
   macro avg       0.97      0.97      0.97        75
weighted avg       0.97      0.97      0.97        75


Confusion Matrix :-
 [[25  0  0]
 [ 0 24  1]
 [ 0  1 24]]


In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
import math

from time import time
import datetime

import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')

TOTAL = df.count()[0]
N_VALID = 90 # Three months
TRAIN = TOTAL - N_VALID
df_small = df.dropna()
features = ['Open', 'High', 'Low', 'Volume']
# features = ['Adj. Open', 'Adj. Low', 'Adj. Close']
X_df = df_small[features]
y_df = df_small['Adj Close']

# X = pd.to_numeric(X_df)
# y = pd.to_numeric(y_df)
X = X_df.to_numpy()
y = y_df.to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
X_train

array([[37813.     , 38098.89844, 37640.39844,  4729.     ],
       [ 3450.     ,  3574.     ,  3400.     ,  5749.     ],
       [34567.     , 34798.89844, 33949.89844,  4655.     ],
       ...,
       [ 7070.     ,  7173.     ,  6985.     , 11228.     ],
       [ 3745.     ,  3748.     ,  3625.     ,  1600.     ],
       [69499.     , 69859.     , 69261.     ,  5505.     ]])

In [16]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
model = RandomForestRegressor(n_estimators=1, max_depth=2, bootstrap=False, min_samples_leaf=1)
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=2,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1, n_jobs=None,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [20]:
#param_grid = {'n_neighbors' : [1,5,10,15], 'weights' : ['uniform','distance']}

param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

clf = GridSearchCV(model, param_grid, cv = 5)

In [21]:
from sklearn import metrics

def mean_absolute_percentage_error(y_true, y_pred): 
    # y_true, y_pred = check_arrays(y_true, y_pred)

    return np.mean(np.abs((y_true - y_pred) / y_true))*100

def rmse(x,y): return math.sqrt(((x-y)**2).mean())

def print_score(m, test_data, model_predictions):
    res = [rmse(m.predict(X_train), y_train), rmse(m.predict(X_test), y_test),
                m.score(X_train, y_train), m.score(X_test, y_test)]
    print(f"rmse train {res[0]}, rmse val {res[1]}, r^2 train {res[2]}, r^2 val {res[3]}")
    
    
    MSE_error = metrics.mean_squared_error(test_data, model_predictions)
    print('Testing Mean Squared Error is {}'.format(MSE_error))

    MAE_error = metrics.mean_absolute_error(test_data, model_predictions)
    print('Testing Mean Absolute Error is {}'.format(MAE_error))

    MAPE_error = mean_absolute_percentage_error(test_data, model_predictions)
    print('Testing Mean Absolute Percentage Error is {}'.format(MAPE_error))

In [22]:
pred = model.predict(X_test)

print_score(model, y_test, pred)

rmse train 4106.177256213923, rmse val 4021.961870829501, r^2 train 0.9671266736876247, r^2 val 0.9689497714683699
Testing Mean Squared Error is 16176177.29040634
Testing Mean Absolute Error is 3167.8231480632285
Testing Mean Absolute Percentage Error is 39.57412570734828
