In [1]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn import datasets,metrics
import pandas as pd

# Iris DataSet

In [2]:
X,y = datasets.load_iris(return_X_y=True)

In [3]:
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

### using entropy

In [4]:
tree = DecisionTreeClassifier(criterion = 'entropy').fit(X_train,y_train)

prediction = tree.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Prediction :- 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 1]

Accuracy score :-
 0.9466666666666667

Classification report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.89      0.96      0.92        25
           2       0.96      0.88      0.92        25

    accuracy                           0.95        75
   macro avg       0.95      0.95      0.95        75
weighted avg       0.95      0.95      0.95        75


Confusion Matrix :-
 [[25  0  0]
 [ 0 24  1]
 [ 0  3 22]]


### using gini index

In [5]:
clf_gini = DecisionTreeClassifier(criterion = "gini").fit(X_train, y_train)

prediction = clf_gini.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Prediction :- 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 1]

Accuracy score :-
 0.9466666666666667

Classification report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.89      0.96      0.92        25
           2       0.96      0.88      0.92        25

    accuracy                           0.95        75
   macro avg       0.95      0.95      0.95        75
weighted avg       0.95      0.95      0.95        75


Confusion Matrix :-
 [[25  0  0]
 [ 0 24  1]
 [ 0  3 22]]


In [6]:
clf_gini.predict([[0,10, 3, 0]])

array([1])

# Categorical dataset - zoo.csv

In [7]:
dataset = pd.read_csv('zoo.csv',names=['animal_name','hair','feathers','eggs','milk',    
                                                   'airbone','aquatic','predator','toothed','backbone',    
                                                  'breathes','venomous','fins','legs','tail','domestic','catsize','class',])  

dataset=dataset.drop('animal_name',axis=1)
dataset['hair'] = pd.to_numeric(dataset['hair'], errors='coerce')
dataset['feathers'] = pd.to_numeric(dataset['feathers'], errors='coerce')
dataset['eggs'] = pd.to_numeric(dataset['eggs'], errors='coerce')
dataset['milk'] = pd.to_numeric(dataset['milk'], errors='coerce')
dataset['airbone'] = pd.to_numeric(dataset['airbone'], errors='coerce')
dataset['aquatic'] = pd.to_numeric(dataset['aquatic'], errors='coerce')
dataset['predator'] = pd.to_numeric(dataset['predator'], errors='coerce')
dataset['toothed'] = pd.to_numeric(dataset['toothed'], errors='coerce')
dataset['backbone'] = pd.to_numeric(dataset['backbone'], errors='coerce')
dataset['breathes'] = pd.to_numeric(dataset['breathes'], errors='coerce')
dataset['venomous'] = pd.to_numeric(dataset['venomous'], errors='coerce')
dataset['fins'] = pd.to_numeric(dataset['fins'], errors='coerce')
dataset['legs'] = pd.to_numeric(dataset['legs'], errors='coerce')
dataset['tail'] = pd.to_numeric(dataset['tail'], errors='coerce')
dataset['domestic'] = pd.to_numeric(dataset['domestic'], errors='coerce')
dataset['catsize'] = pd.to_numeric(dataset['catsize'], errors='coerce')
dataset = dataset.replace(np.nan, 0, regex=True)
print (dataset.dtypes)

hair        float64
feathers    float64
eggs        float64
milk        float64
airbone     float64
aquatic     float64
predator    float64
toothed     float64
backbone    float64
breathes    float64
venomous    float64
fins        float64
legs        float64
tail        float64
domestic    float64
catsize     float64
class        object
dtype: object


In [8]:
X = pd.DataFrame(dataset.iloc[:,:-1])
y = pd.DataFrame(dataset.iloc[:,-1])

X_train = X[:80]
y_train = y[:80]

X_test = X[80:]
y_test = y[80:]

### using entropy

In [9]:
tree = DecisionTreeClassifier(criterion = 'entropy').fit(X_train,y_train)

prediction = tree.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Prediction :- 
 ['2' '3' 'class_type' '4' '2' '1' '7' '4' '2' '6' '5' '6' '5' '4' '1' '1'
 '2' '1' '6' '1' 'class_type' '2']

Accuracy score :-
 0.8181818181818182

Classification report :- 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         5
           3       1.00      0.33      0.50         3
           4       1.00      1.00      1.00         3
           5       0.50      1.00      0.67         1
           6       0.67      1.00      0.80         2
           7       1.00      0.33      0.50         3
  class_type       0.00      0.00      0.00         0

    accuracy                           0.82        22
   macro avg       0.77      0.71      0.68        22
weighted avg       0.95      0.82      0.83        22


Confusion Matrix :-
 [[5 0 0 0 0 0 0 0]
 [0 5 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 2]
 [

C:\Users\labdh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


### using gini index

In [10]:
tree_gini = DecisionTreeClassifier(criterion = 'gini').fit(X_train,y_train)

prediction = tree_gini.predict(X_test)
print("Prediction :- \n",prediction)

print("\nAccuracy score :-\n",metrics.accuracy_score(y_test, prediction, normalize= True))

print("\nClassification report :- \n",metrics.classification_report(y_test, prediction))

print("\nConfusion Matrix :-\n",metrics.confusion_matrix(y_test,prediction))

Prediction :- 
 ['2' '3' '6' '4' '2' '1' '7' '4' '2' '6' '5' '5' '5' '4' '1' '1' '2' '1'
 '6' '1' '6' '2']

Accuracy score :-
 0.8181818181818182

Classification report :- 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         5
           3       1.00      0.33      0.50         3
           4       1.00      1.00      1.00         3
           5       0.33      1.00      0.50         1
           6       0.50      1.00      0.67         2
           7       1.00      0.33      0.50         3

    accuracy                           0.82        22
   macro avg       0.83      0.81      0.74        22
weighted avg       0.92      0.82      0.81        22


Confusion Matrix :-
 [[5 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 0 1 0 2 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 2 1]]


![title](image/1.png)