In [3]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn import datasets,metrics
from sklearn.tree import export_graphviz
import pydotplus

# Iris DataSet

In [4]:
X,y = datasets.load_iris(return_X_y=True)

In [5]:
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]

### using entropy

In [6]:
tree = DecisionTreeClassifier(criterion = 'entropy').fit(X_train,y_train)

In [7]:
export_graphviz(tree, out_file='abc.dot')

![title](image/1.png)

In [8]:
prediction = tree.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
metrics.accuracy_score(y_test, prediction, normalize= True)

0.96

In [10]:
print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



In [11]:
metrics.confusion_matrix(y_test,prediction)

array([[25,  0,  0],
       [ 0, 24,  1],
       [ 0,  2, 23]], dtype=int64)

### using gini index

In [13]:
clf_gini = DecisionTreeClassifier(criterion = "gini").fit(X_train, y_train)

In [19]:
prediction = tree.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
metrics.accuracy_score(y_test, prediction, normalize= True)

0.96

In [21]:
print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



In [22]:
metrics.confusion_matrix(y_test,prediction)

array([[25,  0,  0],
       [ 0, 24,  1],
       [ 0,  2, 23]], dtype=int64)

In [29]:
clf_gini.predict([[0,10, 3, 0]])

array([1])